---
# Tasks cài đặt MySQL 8.0.42 từ binary trên Ubuntu/Debian
- name: Cập nhật apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Cài đặt các packages cần thiết
  apt:
    name:
      - wget
      - tar
      - libaio1
      - libnuma1
      - python3-pymysql
      - libmecab2
      - libtinfo5  # Ubuntu 24.04 compatibility
      - libssl3    # Updated SSL library
    state: present

- name: Tạo thư mục tạm để tải MySQL
  file:
    path: /tmp/mysql-install
    state: directory
    mode: '0755'

- name: Tải MySQL 8.0.42 binary từ MySQL website
  get_url:
    url: "https://dev.mysql.com/get/Downloads/MySQL-8.0/mysql-8.0.42-linux-glibc2.28-x86_64.tar.xz"
    dest: /tmp/mysql-install/mysql-8.0.42-linux-glibc2.28-x86_64.tar.xz
    mode: '0644'
    timeout: 300
  register: mysql_download
  retries: 3
  delay: 10

- name: Hiển thị kết quả download
  debug:
    msg: "📦 MySQL binary: {{ (mysql_download.stat.size / 1024 / 1024) | round(2) if mysql_download.stat is defined else 'Unknown' }} MB"

- name: Kiểm tra nếu MySQL đã được cài đặt trước đó
  stat:
    path: /usr/local/mysql
  register: mysql_existing_install

- name: Backup MySQL cũ nếu tồn tại
  shell: |
    if [ -d "/usr/local/mysql" ]; then
      mv /usr/local/mysql /usr/local/mysql.backup.$(date +%Y%m%d_%H%M%S)
      echo "Backed up existing MySQL installation"
    else
      echo "No existing MySQL installation found"
    fi
  register: backup_result
  when: mysql_existing_install.stat.exists

- name: Hiển thị kết quả backup
  debug:
    msg: "{{ backup_result.stdout }}"
  when: mysql_existing_install.stat.exists

- name: Giải nén MySQL binary
  unarchive:
    src: /tmp/mysql-install/mysql-8.0.42-linux-glibc2.28-x86_64.tar.xz
    dest: /tmp/mysql-install/
    remote_src: yes
    creates: /tmp/mysql-install/mysql-8.0.42-linux-glibc2.28-x86_64

- name: Di chuyển MySQL đến /usr/local/mysql
  shell: |
    mv /tmp/mysql-install/mysql-8.0.42-linux-glibc2.28-x86_64 /usr/local/mysql
    echo "MySQL moved to /usr/local/mysql"
  args:
    creates: /usr/local/mysql

- name: Tạo MySQL group
  group:
    name: "{{ mysql_group }}"
    state: present

- name: Tạo MySQL user
  user:
    name: "{{ mysql_user }}"
    group: "{{ mysql_group }}"
    system: yes
    shell: /bin/false
    home: "{{ mysql_basedir }}"
    create_home: no
    state: present

- name: Tạo thư mục mysql-files
  file:
    path: "{{ mysql_basedir }}/mysql-files"
    state: directory
    owner: "{{ mysql_user }}"
    group: "{{ mysql_group }}"
    mode: '0750'

- name: Tạo thư mục data
  file:
    path: "{{ mysql_datadir }}"
    state: directory
    owner: "{{ mysql_user }}"
    group: "{{ mysql_group }}"
    mode: '0750'

- name: Tạo thư mục logs
  file:
    path: /var/log/mysql
    state: directory
    owner: "{{ mysql_user }}"
    group: "{{ mysql_group }}"
    mode: '0755'

- name: Thiết lập quyền cho MySQL directory
  file:
    path: "{{ mysql_basedir }}"
    owner: "{{ mysql_user }}"
    group: "{{ mysql_group }}"
    recurse: yes
    state: directory

- name: Khởi tạo MySQL database
  shell: |
    cd {{ mysql_basedir }}
    ./bin/mysqld --initialize --user={{ mysql_user }} --datadir={{ mysql_datadir }}
  register: mysql_init_result
  args:
    creates: "{{ mysql_datadir }}/mysql"

- name: Lấy temporary root password từ log
  shell: |
    grep 'temporary password' /var/log/mysql/error.log | awk '{print $NF}' | tail -1
  register: mysql_temp_password
  failed_when: false
  changed_when: false

- name: Hiển thị thông tin khởi tạo
  debug:
    msg: "✅ MySQL initialized | Root password: {{ mysql_temp_password.stdout if mysql_temp_password.stdout else 'Set during secure installation' }}"

- name: Tạo symlink cho MySQL commands
  file:
    src: "{{ mysql_basedir }}/bin/{{ item }}"
    dest: /usr/local/bin/{{ item }}
    state: link
  loop:
    - mysql
    - mysqldump
    - mysqladmin
    - mysqlcheck
  ignore_errors: yes

- name: Cập nhật PATH trong /etc/environment
  lineinfile:
    path: /etc/environment
    regexp: '^PATH='
    line: 'PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:{{ mysql_basedir }}/bin"'
    backup: yes

- name: Hiển thị trạng thái cài đặt
  debug:
    msg: "🎉 MySQL 8.0.42 installed: {{ mysql_basedir }} | Data: {{ mysql_datadir }}"
